import "./globals.css";
import { Inter } from "next/font/google";

export const metadata = {
  title: "Trello 2.0 AI Clone",
  description: "Generated by the Furkan TANRIOVER",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
